project: 
  type: book
  output-dir: _book
  
book:
  title: "Steller Sea Lion Population Monitoring Protocols"
  author: "Burlyn Birkemeier"
  date: last-modified 
  description: "This page contains all protocols related to monitoring the endangered Steller sea lion popuation, including the Aerial Survey Protocol, Counting Protocol, and helpful tips for updating SARS, memos, and Tech memos" 
  
  page-footer:
    left: |
      <a href="http://www.smast.umassd.edu/lab_fay/">The Fay lab</a>
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: https://burlynb.github.io/SSL-Protocols/
  repo-url: https://github.com/burlynb/ASSLAP-Protocols
  repo-actions: [edit,issue]

  chapters: 
    - index.qmd
    - 01-intro-how-we-work.qmd
    - 02-lab-culture-philosophy.qmd
    - 03-code-of-conduct.qmd
    - 04-onboarding.qmd
    - 05-expectations.qmd
    - 06-offboarding.qmd
    - 07-funding.qmd
    - 08-communication.qmd
    - 09-academics.qmd
    - 10-courses.qmd
    - 11-computing.qmd
    - 12-umassd-resources.qmd
#    - 13-smast-resources.qmd
#    - 14-other-faylab-resources.qmd  


# not sure what the following line does; those files are present
bibliography: [references.bib, book.bib]

